// AUTO-GENERATED by `pnpm gen:types` (backend/src/gen-types.ts).
// Do not edit by hand — edit backend/src/contract.ts and regenerate.
//
// Same-origin contract shared with the backend. Kept small and honest so it
// never blocks the build.

/** The four Looka members. */
export type Member = 'frank' | 'juan' | 'suvi' | 'joe'

/** Body sent to `POST /api/<member>/ping`. */
export interface PingRequest {
  /** Optional caller tag, e.g. "looka-room". */
  from?: string
  /** Optional free-text ask from the user, e.g. "give me your report". */
  message?: string
}

/** Reply from `POST /api/<member>/ping`. */
export interface PingResponse {
  /** Member/agent that answered, e.g. "frank". */
  member: string
  /** Human-readable reply text to show in the card. */
  message: string
  /** Whether the agent handled the ping successfully. */
  ok: boolean
}

/** Body sent to `POST /api/bee/ask` — the orchestrator the room talks to. */
export interface BeeAskRequest {
  /** The user's message / transcript. */
  message: string
}

/** Reply from `POST /api/bee/ask`. */
export interface BeeAskResponse {
  /** Whether the orchestrator got a real reply (vs. a placeholder). */
  ok: boolean
  /** Which connector id handled it, or null for general chat. */
  connector: string | null
  /** The reply text. */
  reply: string
}
