// gen:types — write the frontend's committed API types from the canonical
// backend contract (src/contract.ts).
//
// Deliberately simple: no full OpenAPI codegen (that path is flaky and must
// never block the build). We emit a small, hand-shaped `.ts` file plus a JSON
// snapshot of the OpenAPI-ish contract for reference.

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { apiContract, MEMBERS } from './contract'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '../..')

const FRONTEND_TYPES = resolve(repoRoot, 'frontend/src/shared/api-types.ts')
const CONTRACT_JSON = resolve(here, 'contract.generated.json')

const membersUnion = MEMBERS.map(m => `'${m}'`).join(' | ')

const tsContent = `// AUTO-GENERATED by \`pnpm gen:types\` (backend/src/gen-types.ts).
// Do not edit by hand — edit backend/src/contract.ts and regenerate.
//
// Same-origin contract shared with the backend. Kept small and honest so it
// never blocks the build.

/** The four Looka members. */
export type Member = ${membersUnion}

/** Body sent to \`POST /api/<member>/ping\`. */
export interface PingRequest {
  /** Optional caller tag, e.g. "looka-room". */
  from?: string
  /** Optional free-text ask from the user, e.g. "give me your report". */
  message?: string
}

/** Reply from \`POST /api/<member>/ping\`. */
export interface PingResponse {
  /** Member/agent that answered, e.g. "frank". */
  member: string
  /** Human-readable reply text to show in the card. */
  message: string
  /** Whether the agent handled the ping successfully. */
  ok: boolean
}

/** Body sent to \`POST /api/bee/ask\` — the orchestrator the room talks to. */
export interface BeeAskRequest {
  /** The user's message / transcript. */
  message: string
}

/** Reply from \`POST /api/bee/ask\`. */
export interface BeeAskResponse {
  /** Whether the orchestrator got a real reply (vs. a placeholder). */
  ok: boolean
  /** Which connector id handled it, or null for general chat. */
  connector: string | null
  /** The reply text. */
  reply: string
}

/** Reply from \`POST /api/bee/voice\` (request = multipart field "audio"). */
export interface BeeVoiceResponse {
  /** Whether the orchestrator got a real reply (vs. a placeholder). */
  ok: boolean
  /** What the STT heard — shown so the user can verify. */
  transcript: string
  /** Which connector id handled it, or null for general chat. */
  connector: string | null
  /** The spoken reply text (bee-composed). */
  reply: string
  /** Base64 mp3 of the reply, or null if synthesis failed. */
  audio: string | null
  /** MIME type of \`audio\` — always "audio/mpeg" today. */
  audioType: string
}
`

mkdirSync(dirname(FRONTEND_TYPES), { recursive: true })
writeFileSync(FRONTEND_TYPES, tsContent)
writeFileSync(CONTRACT_JSON, `${JSON.stringify(apiContract, null, 2)}\n`)

// eslint-disable-next-line no-console
console.log(`[gen:types] wrote ${FRONTEND_TYPES}`)
